//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.24 at 07:13:51 PM IST 
//


package com.wordpress.code2blog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wordpress.code2blog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FIRSTNAME_QNAME = new QName("", "FIRSTNAME");
    private final static QName _CACHEUPDATEDAT_QNAME = new QName("", "CACHE_UPDATED_AT");
    private final static QName _EMPNO_QNAME = new QName("", "EMPNO");
    private final static QName _LASTNAME_QNAME = new QName("", "LASTNAME");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wordpress.code2blog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EMPLOYEE }
     * 
     */
    public EMPLOYEE createEMPLOYEE() {
        return new EMPLOYEE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRSTNAME")
    public JAXBElement<String> createFIRSTNAME(String value) {
        return new JAXBElement<String>(_FIRSTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CACHE_UPDATED_AT")
    public JAXBElement<String> createCACHEUPDATEDAT(String value) {
        return new JAXBElement<String>(_CACHEUPDATEDAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMPNO")
    public JAXBElement<Integer> createEMPNO(Integer value) {
        return new JAXBElement<Integer>(_EMPNO_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LASTNAME")
    public JAXBElement<String> createLASTNAME(String value) {
        return new JAXBElement<String>(_LASTNAME_QNAME, String.class, null, value);
    }

}
